#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/bridge
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dusch0627

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show_sql: true
    defer-datasource-initialization: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

apple:
  team.id: K9M6C75JFU
  key.id: PHWF68YA49
  client.id: com.bridge.project.services
  redirect.url: https://bridge.com/return
  key.path: /Users/kh/Desktop/static/AuthKey_PHWF68YA49.p8
  iss: https://appleid.apple.com

