#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/bridge
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bridge?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: dusch0627

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
      show_sql: true

  springdoc:
    packages-to-scan: com.Bridge.bridge.controller
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      path: /swagger-ui.html
      disable-swagger-default-url: true
      display-request-duration: true
      operations-sorter: alpha
      tags-sorter: alpha


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


jwt :
  secret-key : VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa